ARG NUGET_GITHUB_CYCODEHQ_PASSWORD=secret_value
ARG ENV=alpine_v6

FROM cycodehq.jfrog.io/minio:staging AS build-env
MAINTAINER ronam
ARG NUGET_GITHUB_CYCODEHQ_PASSWORD
WORKDIR /app

# Copy csproj and restore as some distinct layers
COPY ./CommonProjectFile ./CommonProjectFile
COPY ./Cycode.Marketplace.Runners.GitCloner ./Cycode.Marketplace.Runners.GitCloner
WORKDIR /app/Cycode.Marketplace.Runners.GitCloner/Cycode.GitCloner.EntryPoint

# Configure cycode nuget repoitory, More info in /README.md file
COPY ./_nuget.config /tmp/nugekt.config
RUN dotnet restore --configfile /tmp/nuget.config

RUN apk add -U curl=7.83.1-r3 bash=5.1.16-r2 ca-certificates=20220614-r0 openssl=1.1.1q-r0 ncurses=6.3_p20220521-r0 \
    coreutils=9.1-r0 make=4.3-r0 gcc=11.2.1_git20220219-r2 g++=11.2.1_git20220219-r2 libgcc=11.2.1_git20220219-r2 \
    linux-headers=5.16.7-r1 grep=3.7-r0 util-linux=2.38-r1 binutils=2.38-r3 findutils=4.9.0-r0

###### test ######
FROM build-env AS test
ARG NUGET_GITHUB_CYCODEHQ_PASSWORD
ARG TESTS_DIR
COPY --from=build-env ./${TESTS_DIR} /app/${TESTS_DIR}
COPY --from=0 ./_nuget.config /tmp/nuget.config
WORKDIR /app/${TESTS_DIR}
RUN sh -c '[ -z "${TESTS_DIR}" ]' || dotnet restore --configfile /tmp/nuget.config
USER cycode
RUN "cd workdir"
CMD ["dotnet", "test","--no-restore","--verbosity" ,"minimal" ,"--filter" ,"Category!=Integration","--collect:\"XPlat Code Coverage\"","--logger:trx"]

###### runtime image ######
FROM cycodehq.jfrog.io/idans/test3repo@sha256:1ab4ce81b2bf00f31bf214586cfc743778c009caeb69c0469a6cade0f71820d4 AS app
WORKDIR /app
ARG VERSION
RUN echo "$VERSION" >>VERSION.txt
COPY --from=build-env /app/Cycode.Marketplace.Runners.GitCloner/Cycode.GitCloner.EntryPoint/out .
USER rrr
ENTRYPOINT ["dotnet", "Cycode.GitCloner.EntryPoint.dll"]
